version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: aimvector/zookeeper:2.7.0
    build:
      context: ./zookeeper
    volumes:
    - ./zookeeper/conf/zookeeper.properties:/kafka/config/zookeeper.properties
  kafka-1:
    container_name: kafka-1
    image: aimvector/kafka:2.7.0
    build:
      context: ./
    volumes:
    - ./Kafka/conf/kafka-1/server.properties:/kafka/config/server.properties
    - ./ressources/kafka/containers_data/kafka-1/kafka_logs:/tmp/kafka-logs/
  kafka-2:
    container_name: kafka-2
    image: aimvector/kafka:2.7.0
    build:
      context: ./
    volumes:
      - ./Kafka/conf/kafka-2/server.properties:/kafka/config/server.properties
      - ./ressources/kafka/containers_data/kafka-2/kafka_logs:/tmp/kafka-logs/